server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb+srv://bkb647087:rtbtdAF2Chc7o1Ed@cluster0.gvo3agp.mongodb.net/microservice
  application:
      name: RATING-SERVICE

  config:    
    import: optional:configserver:http://localhost:8085
          
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/    